version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
  pre_build:
    commands:
      - dotnet restore RegexTester
  build:
    commands:
      - dotnet test RegexTesterTest
      - dotnet publish -c Release -warnaserror RegexTester
artifacts:
  files:
    - '**/*'
  base-directory: RegexTester/bin/Release/net6.0/publish/wwwroot
