name: check code

on: [push]

jobs: 
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'
      - name: Install ReSharper Command Line Tool
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
      - name: Run Inspection
        run: jb inspect RegexTester.sln --dotnetcoresdk=5.0.102
  
