name: check_pull_request

on: pull_request

jobs: 
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore
        run: dotnet restore RegexTester
      - name: Build
        run: dotnet build --no-restore -warnAsError RegexTester
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Test
        run: dotnet test RegexTesterTest
  
