name: deploy
on:
  push:
    branches:
      - master

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore
        run: dotnet restore RegexTester
      - name: Build
        run: dotnet build --no-restore -warnAsError RegexTester
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Test
        run: dotnet test RegexTesterTest
  deploy:
    needs: [code_analysis,test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Build
        run: dotnet publish -c Release RegexTester
      - name: Deploy
        uses: peaceiris/actions-gh-pages@e4724d9526ddfb09b07b596f47dda5cee7b3f14b
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./RegexTester/bin/Release/net5.0/publish/wwwroot
